export type { WindowConfig, WindowPosition, TilesLayout, PlatformName } from './types'
export * from './platformWindow'
export * from './platform'
export * from './getPlatformAsync'
export { PlatformProvider, usePlatform } from './platformContext'
