type News{
    author: String!
    title: String!
    description: String!
    url: String!
    urlToImage: String!
    publishedAt: String!
}

type StockIndex {
  price: Price!
}

type Stock {
    id: String!
    name: String!
    # … company static fields

    attributes: StockSummary,
    analytics: StockAnalytics,
    peers(count: Int = 5): [Stock!],
    relatedNews(count: Int = 10): [News!]!
    relatedIndex: [StockIndex]
}

type StockSummary {
  latestPrice: Price!
  daysRange: String!
  fiftyTwoWeekRange: String!
  avgVolume: Float!
  marketCap: String!
}

type StockAnalytics {
  history(tenor: String!): Price
  # … historical pricing, predictions, etc.
}

type Price {
    date: String!
    open: Float!
    low: Float!
    high: Float!
    close: Float!
    volume: Int!
}

type Query {
    stockInfo(id: String): Stock!
}

type Subscription {
    price(id: ID!): Price
    indices(ids: [ID!]!): [StockIndex]
    stockSummaryUpdate(ids: [ID!]!): [StockSummary]
}

schema {
    query: Query
    subscription: Subscription
}
