type ChartDataPoint {
  date: Date
  minute: Time
  label: String
  high: Float
  low: Float
  average: Float
  volume: Flaot
  notional: Flaot,
  numberOfTrades: Float
  changeOverTime: Float
  marktHigh: Float
  marketLow: Float
  marketAverage: Float
  marketVolume: Float
  marketNotional: Float
  marketNumberOfTrades: Float
  marketChangeOverTime: Float
}
