export default [
  {
    "security": "United Kingdom 1Y Yield (TPI)",
    "yield": 0.45,
    "change": -0.02,
    "percentChange": "-4.34%",
    "WTDChg": "-2.06%",
    "OneMonthChange": "4.41%",
    "ThreeMonthChange": "93.00%",
    "TwelveMonthChange": "293.04%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 1.25,
    "maturityDate": "22-Jul-18"
  },
  {
    "security": "United Kingdom 2Y Yield (TPI)",
    "yield": 0.47,
    "change": -0.02,
    "percentChange": "-4.66%",
    "WTDChg": "1.91%",
    "OneMonthChange": "-1.51%",
    "ThreeMonthChange": "110.79%",
    "TwelveMonthChange": "134.15%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 1.75,
    "maturityDate": "22-Jul-19"
  },
  {
    "security": "United Kingdom 3Y Yield (TPI)",
    "yield": 0.51,
    "change": -0.02,
    "percentChange": "-4.39%",
    "WTDChg": "1.30%",
    "OneMonthChange": "-9.67%",
    "ThreeMonthChange": "116.35%",
    "TwelveMonthChange": "64.77%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 2,
    "maturityDate": "22-Jul-20"
  },
  {
    "security": "United Kingdom 4Y Yield (TPI)",
    "yield": 0.55,
    "change": -0.04,
    "percentChange": "-6.01%",
    "WTDChg": "1.63%",
    "OneMonthChange": "-10.76%",
    "ThreeMonthChange": "84.97%",
    "TwelveMonthChange": "6.15%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 1.5,
    "maturityDate": "22-Jan-21"
  },
  {
    "security": "United Kingdom 5Y Yield (TPI)",
    "yield": 0.73,
    "change": -0.05,
    "percentChange": "-5.79%",
    "WTDChg": "4.42%",
    "OneMonthChange": "-9.36%",
    "ThreeMonthChange": "52.95%",
    "TwelveMonthChange": "17.82%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 0.5,
    "maturityDate": "22-Jul-22"
  },
  {
    "security": "United Kingdom 6Y Yield (TPI)",
    "yield": 0.85,
    "change": -0.05,
    "percentChange": "-5.53%",
    "WTDChg": "3.75%",
    "OneMonthChange": "-7.83%",
    "ThreeMonthChange": "42.21%",
    "TwelveMonthChange": "3.78%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 2.25,
    "maturityDate": "07-Sep-23"
  },
  {
    "security": "United Kingdom 7Y Yield (TPI)",
    "yield": 0.96,
    "change": -0.05,
    "percentChange": "-4.90%",
    "WTDChg": "4.09%",
    "OneMonthChange": "-7.13%",
    "ThreeMonthChange": "33.05%",
    "TwelveMonthChange": "-0.35%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 2.75,
    "maturityDate": "07-Sep-24"
  },
  {
    "security": "United Kingdom 8Y Yield (TPI)",
    "yield": 1.07,
    "change": -0.05,
    "percentChange": "-4.60%",
    "WTDChg": "4.30%",
    "OneMonthChange": "-7.49%",
    "ThreeMonthChange": "26.69%",
    "TwelveMonthChange": "-4.83%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 2,
    "maturityDate": "07-Sep-25"
  },
  {
    "security": "United Kingdom 9Y Yield (TPI)",
    "yield": 1.17,
    "change": -0.05,
    "percentChange": "-4.34%",
    "WTDChg": "3.66%",
    "OneMonthChange": "-7.93%",
    "ThreeMonthChange": "20.41%",
    "TwelveMonthChange": "-1.22%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 1.5,
    "maturityDate": "22-Jul-26"
  },
  {
    "security": "United Kingdom 10Y Yield (TPI)",
    "yield": 1.27,
    "change": -0.05,
    "percentChange": "-3.97%",
    "WTDChg": "3.50%",
    "OneMonthChange": "-8.05%",
    "ThreeMonthChange": "18.48%",
    "TwelveMonthChange": "1.06%",
    "modDur": "8.35%",
    "moodysRating": "Aa2",
    "coupon": 4.25,
    "maturityDate": "07-Dec-27"
  },
  {
    "security": "United Kingdom 12Y Yield (TPI)",
    "yield": 1.5,
    "change": -0.05,
    "percentChange": "-3.22%",
    "WTDChg": "3.20%",
    "OneMonthChange": "-6.31%",
    "ThreeMonthChange": "13.22%",
    "TwelveMonthChange": "0.59%",
    "modDur": "",
    "moodysRating": "Aa2",
    "coupon": 4.75,
    "maturityDate": "07-Dec-30"
  },
  {
    "security": "United Kingdom 15Y Yield (TPI)",
    "yield": 1.61,
    "change": -0.05,
    "percentChange": "-3.04%",
    "WTDChg": "2.82%",
    "OneMonthChange": "-5.72%",
    "ThreeMonthChange": "11.89%",
    "TwelveMonthChange": "-7.44%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 4.25,
    "maturityDate": "07-Jun-32"
  },
  {
    "security": "United Kingdom 20Y Yield (TPI)",
    "yield": 1.76,
    "change": -0.05,
    "percentChange": "-2.82%",
    "WTDChg": "2.36%",
    "OneMonthChange": "-5.55%",
    "ThreeMonthChange": "9.29%",
    "TwelveMonthChange": "-7.43%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 4.25,
    "maturityDate": "07-Mar-36"
  },
  {
    "security": "United Kingdom 25Y Yield (TPI)",
    "yield": 1.86,
    "change": -0.05,
    "percentChange": "-2.52%",
    "WTDChg": "2.24%",
    "OneMonthChange": "-5.01%",
    "ThreeMonthChange": "7.63%",
    "TwelveMonthChange": "-6.36%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 4.5,
    "maturityDate": "07-Dec-42"
  },
  {
    "security": "United Kingdom 30Y Yield (TPI)",
    "yield": 1.85,
    "change": -0.05,
    "percentChange": "-2.44%",
    "WTDChg": "2.54%",
    "OneMonthChange": "-4.95%",
    "ThreeMonthChange": "7.29%",
    "TwelveMonthChange": "-8.32%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 1.5,
    "maturityDate": "22-Jul-47"
  },
  {
    "security": "Australia 1Y Yield (TPI)",
    "yield": 1.7,
    "change": -0.01,
    "percentChange": "-0.31%",
    "WTDChg": "-0.41%",
    "OneMonthChange": "-4.68%",
    "ThreeMonthChange": "4.12%",
    "TwelveMonthChange": "-0.45%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 3.25,
    "maturityDate": "21-Oct-18"
  },
  {
    "security": "Australia 2Y Yield (TPI)",
    "yield": 1.78,
    "change": -0.04,
    "percentChange": "-2.16%",
    "WTDChg": "-0.22%",
    "OneMonthChange": "-7.50%",
    "ThreeMonthChange": "0.41%",
    "TwelveMonthChange": "1.39%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 2.75,
    "maturityDate": "21-Oct-19"
  },
  {
    "security": "Australia 3Y Yield (TPI)",
    "yield": 1.93,
    "change": -0.05,
    "percentChange": "-2.76%",
    "WTDChg": "-0.12%",
    "OneMonthChange": "-8.41%",
    "ThreeMonthChange": "-1.19%",
    "TwelveMonthChange": "5.93%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 1.75,
    "maturityDate": "21-Nov-20"
  },
  {
    "security": "Australia 4Y Yield (TPI)",
    "yield": 2.07,
    "change": -0.05,
    "percentChange": "-2.42%",
    "WTDChg": "-0.05%",
    "OneMonthChange": "-8.69%",
    "ThreeMonthChange": "-1.47%",
    "TwelveMonthChange": "6.81%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 2,
    "maturityDate": "21-Dec-21"
  },
  {
    "security": "Australia 5Y Yield (TPI)",
    "yield": 2.12,
    "change": -0.05,
    "percentChange": "-2.41%",
    "WTDChg": "-0.14%",
    "OneMonthChange": "-8.32%",
    "ThreeMonthChange": "-0.79%",
    "TwelveMonthChange": "-1.18%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 5.75,
    "maturityDate": "15-Jul-22"
  },
  {
    "security": "Australia 7Y Yield (TPI)",
    "yield": 2.43,
    "change": -0.05,
    "percentChange": "-2.12%",
    "WTDChg": "0.18%",
    "OneMonthChange": "-3.94%",
    "ThreeMonthChange": "3.26%",
    "TwelveMonthChange": "-0.07%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 3.25,
    "maturityDate": "21-Apr-25"
  },
  {
    "security": "Australia 9Y Yield (TPI)",
    "yield": 2.55,
    "change": -0.05,
    "percentChange": "-2.07%",
    "WTDChg": "0.29%",
    "OneMonthChange": "-5.56%",
    "ThreeMonthChange": "1.35%",
    "TwelveMonthChange": "-2.03%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 4.75,
    "maturityDate": "21-Apr-27"
  },
  {
    "security": "Australia 10Y Yield (TPI)",
    "yield": 2.59,
    "change": -0.06,
    "percentChange": "-2.11%",
    "WTDChg": "0.17%",
    "OneMonthChange": "-7.20%",
    "ThreeMonthChange": "-0.62%",
    "TwelveMonthChange": "-2.28%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 2.75,
    "maturityDate": "21-Nov-27"
  },
  {
    "security": "Australia 15Y Yield (TPI)",
    "yield": 2.87,
    "change": -0.05,
    "percentChange": "-1.77%",
    "WTDChg": "0.40%",
    "OneMonthChange": "-6.79%",
    "ThreeMonthChange": "-1.28%",
    "TwelveMonthChange": "-7.74%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 4.5,
    "maturityDate": "21-Apr-33"
  },
  {
    "security": "Belgium 1Y Yield (TPI)",
    "yield": -0.74,
    "change": -0.02,
    "percentChange": "3.47%",
    "WTDChg": "3.54%",
    "OneMonthChange": "15.36%",
    "ThreeMonthChange": "24.83%",
    "TwelveMonthChange": "-9.90%",
    "modDur": "--",
    "moodysRating": "Aa3",
    "coupon": 1.25,
    "maturityDate": "22-Jun-18"
  },
  {
    "security": "Belgium 2Y Yield (TPI)",
    "yield": -0.64,
    "change": -0.02,
    "percentChange": "2.72%",
    "WTDChg": "-0.62%",
    "OneMonthChange": "13.79%",
    "ThreeMonthChange": "13.48%",
    "TwelveMonthChange": "8.69%",
    "modDur": "--",
    "moodysRating": "Aa3",
    "coupon": 3,
    "maturityDate": "28-Sep-19"
  },
  {
    "security": "Belgium 3Y Yield (TPI)",
    "yield": -0.58,
    "change": -0.02,
    "percentChange": "4.26%",
    "WTDChg": "-2.19%",
    "OneMonthChange": "16.65%",
    "ThreeMonthChange": "19.58%",
    "TwelveMonthChange": "37.39%",
    "modDur": "--",
    "moodysRating": "Aa3",
    "coupon": 3.75,
    "maturityDate": "28-Sep-20"
  },
  {
    "security": "Belgium 4Y Yield (TPI)",
    "yield": -0.47,
    "change": -0.03,
    "percentChange": "5.96%",
    "WTDChg": "-1.94%",
    "OneMonthChange": "21.01%",
    "ThreeMonthChange": "29.19%",
    "TwelveMonthChange": "44.18%",
    "modDur": "--",
    "moodysRating": "Aa3",
    "coupon": 4.25,
    "maturityDate": "28-Sep-21"
  },
  {
    "security": "Belgium 6Y Yield (TPI)",
    "yield": -0.15,
    "change": -0.03,
    "percentChange": "22.14%",
    "WTDChg": "-9.04%",
    "OneMonthChange": "171.93%",
    "ThreeMonthChange": "278.97%",
    "TwelveMonthChange": "209.38%",
    "modDur": "--",
    "moodysRating": "Aa3",
    "coupon": 2.25,
    "maturityDate": "22-Jun-23"
  },
  {
    "security": "Belgium 7Y Yield (TPI)",
    "yield": 0.04,
    "change": -0.03,
    "percentChange": "-43.18%",
    "WTDChg": "44.93%",
    "OneMonthChange": "-75.90%",
    "ThreeMonthChange": "-77.67%",
    "TwelveMonthChange": "-34.75%",
    "modDur": "--",
    "moodysRating": "Aa3",
    "coupon": 2.6,
    "maturityDate": "22-Jun-24"
  },
  {
    "security": "Belgium 9Y Yield (TPI)",
    "yield": 0.39,
    "change": -0.04,
    "percentChange": "-9.50%",
    "WTDChg": "2.12%",
    "OneMonthChange": "-28.19%",
    "ThreeMonthChange": "-29.12%",
    "TwelveMonthChange": "-20.52%",
    "modDur": "--",
    "moodysRating": "Aa3",
    "coupon": 1,
    "maturityDate": "22-Jun-26"
  },
  {
    "security": "Belgium 10Y Yield (TPI)",
    "yield": 0.57,
    "change": -0.04,
    "percentChange": "-6.37%",
    "WTDChg": "1.18%",
    "OneMonthChange": "-21.75%",
    "ThreeMonthChange": "-20.88%",
    "TwelveMonthChange": "-14.03%",
    "modDur": "--",
    "moodysRating": "Aa3",
    "coupon": 0.8,
    "maturityDate": "22-Jun-27"
  },
  {
    "security": "Belgium 15Y Yield (TPI)",
    "yield": 0.97,
    "change": -0.04,
    "percentChange": "-4.03%",
    "WTDChg": "1.15%",
    "OneMonthChange": "-12.76%",
    "ThreeMonthChange": "-9.92%",
    "TwelveMonthChange": "-7.81%",
    "modDur": "--",
    "moodysRating": "Aa3",
    "coupon": 1,
    "maturityDate": "22-Jun-31"
  },
  {
    "security": "Belgium 30Y Yield (TPI)",
    "yield": 1.68,
    "change": -0.05,
    "percentChange": "-2.66%",
    "WTDChg": "0.56%",
    "OneMonthChange": "-5.56%",
    "ThreeMonthChange": "-1.78%",
    "TwelveMonthChange": "6.60%",
    "modDur": "--",
    "moodysRating": "Aa3",
    "coupon": 1.6,
    "maturityDate": "22-Jun-47"
  },
  {
    "security": "Canada 10Y Yield (TPI)",
    "yield": 1.92,
    "change": -0.03,
    "percentChange": "-1.64%",
    "WTDChg": "1.28%",
    "OneMonthChange": "-7.70%",
    "ThreeMonthChange": "2.24%",
    "TwelveMonthChange": "24.80%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 1,
    "maturityDate": "01-Jun-27"
  },
  {
    "security": "Canada 2Y Yield (TPI)",
    "yield": 1.44,
    "change": -0.03,
    "percentChange": "-2.17%",
    "WTDChg": "1.64%",
    "OneMonthChange": "-8.74%",
    "ThreeMonthChange": "16.58%",
    "TwelveMonthChange": "114.38%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 1.25,
    "maturityDate": "01-Nov-19"
  },
  {
    "security": "Canada 3Y Yield (TPI)",
    "yield": "--",
    "change": "--",
    "percentChange": "--",
    "WTDChg": "--",
    "OneMonthChange": "--",
    "ThreeMonthChange": "--",
    "TwelveMonthChange": "--",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": "--",
    "maturityDate": "--"
  },
  {
    "security": "Canada 4Y Yield (TPI)",
    "yield": 1.54,
    "change": -0.02,
    "percentChange": "-1.27%",
    "WTDChg": "2.31%",
    "OneMonthChange": "-6.22%",
    "ThreeMonthChange": "12.94%",
    "TwelveMonthChange": "85.43%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0.75,
    "maturityDate": "01-Mar-21"
  },
  {
    "security": "Canada 5Y Yield (TPI)",
    "yield": 1.64,
    "change": -0.03,
    "percentChange": "-1.72%",
    "WTDChg": "2.23%",
    "OneMonthChange": "-6.57%",
    "ThreeMonthChange": "10.44%",
    "TwelveMonthChange": "72.84%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 1,
    "maturityDate": "01-Sep-22"
  },
  {
    "security": "Canada 6Y Yield (TPI)",
    "yield": 1.69,
    "change": -0.03,
    "percentChange": "-1.92%",
    "WTDChg": "1.66%",
    "OneMonthChange": "-7.28%",
    "ThreeMonthChange": "5.74%",
    "TwelveMonthChange": "61.23%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 1.5,
    "maturityDate": "01-Jun-23"
  },
  {
    "security": "Canada 7Y Yield (TPI)",
    "yield": 1.75,
    "change": -0.03,
    "percentChange": "-1.80%",
    "WTDChg": "1.48%",
    "OneMonthChange": "-7.95%",
    "ThreeMonthChange": "4.29%",
    "TwelveMonthChange": "46.90%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 2.5,
    "maturityDate": "01-Jun-24"
  },
  {
    "security": "Canada 8Y Yield (TPI)",
    "yield": 1.8,
    "change": -0.04,
    "percentChange": "-1.91%",
    "WTDChg": "1.33%",
    "OneMonthChange": "-8.34%",
    "ThreeMonthChange": "2.84%",
    "TwelveMonthChange": "35.95%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 2.25,
    "maturityDate": "01-Jun-25"
  },
  {
    "security": "Canada 9Y Yield (TPI)",
    "yield": 1.86,
    "change": -0.03,
    "percentChange": "-1.83%",
    "WTDChg": "1.25%",
    "OneMonthChange": "-8.34%",
    "ThreeMonthChange": "2.35%",
    "TwelveMonthChange": "29.26%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 1.5,
    "maturityDate": "01-Jun-26"
  },
  {
    "security": "Canada 20Y Yield (TPI)",
    "yield": 2.2,
    "change": -0.03,
    "percentChange": "-1.21%",
    "WTDChg": "1.02%",
    "OneMonthChange": "-7.94%",
    "ThreeMonthChange": "-2.70%",
    "TwelveMonthChange": "3.50%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 5,
    "maturityDate": "01-Jun-37"
  },
  {
    "security": "Canada 30Y Yield (TPI)",
    "yield": 2.25,
    "change": -0.03,
    "percentChange": "-1.15%",
    "WTDChg": "1.21%",
    "OneMonthChange": "-7.55%",
    "ThreeMonthChange": "-2.91%",
    "TwelveMonthChange": "3.99%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 2.75,
    "maturityDate": "01-Dec-48"
  },
  {
    "security": "Denmark 1Y Yield (TPI)",
    "yield": "--",
    "change": "--",
    "percentChange": "--",
    "WTDChg": "--",
    "OneMonthChange": "--",
    "ThreeMonthChange": "--",
    "TwelveMonthChange": "--",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": "--",
    "maturityDate": "--"
  },
  {
    "security": "Denmark 2Y Yield (TPI)",
    "yield": -0.67,
    "change": 0,
    "percentChange": "-0.67%",
    "WTDChg": "2.83%",
    "OneMonthChange": "6.89%",
    "ThreeMonthChange": "9.96%",
    "TwelveMonthChange": "16.90%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0.25,
    "maturityDate": "15-Nov-18"
  },
  {
    "security": "Denmark 3Y Yield (TPI)",
    "yield": -0.64,
    "change": 0,
    "percentChange": "-0.25%",
    "WTDChg": "2.70%",
    "OneMonthChange": "9.80%",
    "ThreeMonthChange": "12.83%",
    "TwelveMonthChange": "45.84%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 4,
    "maturityDate": "15-Nov-19"
  },
  {
    "security": "Denmark 4Y Yield (TPI)",
    "yield": "--",
    "change": "--",
    "percentChange": "--",
    "WTDChg": "--",
    "OneMonthChange": "--",
    "ThreeMonthChange": "--",
    "TwelveMonthChange": "--",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": "--",
    "maturityDate": "--"
  },
  {
    "security": "Denmark 5Y Yield (TPI)",
    "yield": -0.42,
    "change": -0.02,
    "percentChange": "5.81%",
    "WTDChg": "1.97%",
    "OneMonthChange": "25.26%",
    "ThreeMonthChange": "28.88%",
    "TwelveMonthChange": "146.37%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 3,
    "maturityDate": "15-Nov-21"
  },
  {
    "security": "Denmark 6Y Yield (TPI)",
    "yield": "--",
    "change": "--",
    "percentChange": "--",
    "WTDChg": "--",
    "OneMonthChange": "--",
    "ThreeMonthChange": "--",
    "TwelveMonthChange": "--",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": "--",
    "maturityDate": "--"
  },
  {
    "security": "Denmark 7Y Yield (TPI)",
    "yield": "--",
    "change": "--",
    "percentChange": "--",
    "WTDChg": "--",
    "OneMonthChange": "--",
    "ThreeMonthChange": "--",
    "TwelveMonthChange": "--",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": "--",
    "maturityDate": "--"
  },
  {
    "security": "Denmark 9Y Yield (TPI)",
    "yield": "--",
    "change": "--",
    "percentChange": "--",
    "WTDChg": "--",
    "OneMonthChange": "--",
    "ThreeMonthChange": "--",
    "TwelveMonthChange": "--",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": "--",
    "maturityDate": "--"
  },
  {
    "security": "Denmark 10Y Yield (TPI)",
    "yield": 0.45,
    "change": -0.03,
    "percentChange": "-5.62%",
    "WTDChg": "8.92%",
    "OneMonthChange": "-18.93%",
    "ThreeMonthChange": "-18.18%",
    "TwelveMonthChange": "17.11%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0.5,
    "maturityDate": "15-Nov-27"
  },
  {
    "security": "Denmark 20Y Yield (TPI)",
    "yield": 1.59,
    "change": 0,
    "percentChange": "-0.07%",
    "WTDChg": "-0.07%",
    "OneMonthChange": "-0.07%",
    "ThreeMonthChange": "-0.07%",
    "TwelveMonthChange": "-0.07%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 7,
    "maturityDate": "10-Nov-24"
  },
  {
    "security": "France 1Y Yield (TPI)",
    "yield": -0.67,
    "change": -0.01,
    "percentChange": "1.37%",
    "WTDChg": "0.18%",
    "OneMonthChange": "11.93%",
    "ThreeMonthChange": "13.87%",
    "TwelveMonthChange": "0.80%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 4.25,
    "maturityDate": "25-Oct-18"
  },
  {
    "security": "France 2Y Yield (TPI)",
    "yield": -0.6,
    "change": -0.02,
    "percentChange": "3.27%",
    "WTDChg": "-2.39%",
    "OneMonthChange": "19.78%",
    "ThreeMonthChange": "20.48%",
    "TwelveMonthChange": "3.93%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 1,
    "maturityDate": "25-Feb-20"
  },
  {
    "security": "France 3Y Yield (TPI)",
    "yield": -0.44,
    "change": -0.02,
    "percentChange": "5.71%",
    "WTDChg": "-4.04%",
    "OneMonthChange": "25.21%",
    "ThreeMonthChange": "-9.56%",
    "TwelveMonthChange": "-9.41%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 0.5,
    "maturityDate": "25-May-21"
  },
  {
    "security": "France 4Y Yield (TPI)",
    "yield": -0.29,
    "change": -0.03,
    "percentChange": "12.46%",
    "WTDChg": "-2.64%",
    "OneMonthChange": "68.22%",
    "ThreeMonthChange": "-13.33%",
    "TwelveMonthChange": "-12.38%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 0.25,
    "maturityDate": "25-May-22"
  },
  {
    "security": "France 5Y Yield (TPI)",
    "yield": -0.13,
    "change": -0.03,
    "percentChange": "34.91%",
    "WTDChg": "-7.49%",
    "OneMonthChange": "1694.52%",
    "ThreeMonthChange": "-10.40%",
    "TwelveMonthChange": "-7.88%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 0,
    "maturityDate": "25-Mar-23"
  },
  {
    "security": "France 6Y Yield (TPI)",
    "yield": 0.02,
    "change": -0.03,
    "percentChange": "-63.46%",
    "WTDChg": "900.00%",
    "OneMonthChange": "-207.95%",
    "ThreeMonthChange": "-271.17%",
    "TwelveMonthChange": "-137.48%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 2.25,
    "maturityDate": "25-May-24"
  },
  {
    "security": "France 7Y Yield (TPI)",
    "yield": 0.2,
    "change": -0.03,
    "percentChange": "-14.57%",
    "WTDChg": "11.48%",
    "OneMonthChange": "38.31%",
    "ThreeMonthChange": "33.68%",
    "TwelveMonthChange": "62.94%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 0.5,
    "maturityDate": "25-May-25"
  },
  {
    "security": "France 8Y Yield (TPI)",
    "yield": 0.38,
    "change": -0.04,
    "percentChange": "-8.89%",
    "WTDChg": "4.12%",
    "OneMonthChange": "7.88%",
    "ThreeMonthChange": "2.02%",
    "TwelveMonthChange": "39.08%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 0.5,
    "maturityDate": "25-May-26"
  },
  {
    "security": "France 9Y Yield (TPI)",
    "yield": 0.56,
    "change": -0.04,
    "percentChange": "-6.60%",
    "WTDChg": "3.52%",
    "OneMonthChange": "2.45%",
    "ThreeMonthChange": "1.15%",
    "TwelveMonthChange": "15.81%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 1,
    "maturityDate": "25-May-27"
  },
  {
    "security": "France 10Y Yield (TPI)",
    "yield": 0.72,
    "change": -0.04,
    "percentChange": "-4.83%",
    "WTDChg": "3.81%",
    "OneMonthChange": "-17.11%",
    "ThreeMonthChange": "2.61%",
    "TwelveMonthChange": "-1.55%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 0.75,
    "maturityDate": "25-May-28"
  },
  {
    "security": "France 15Y Yield (TPI)",
    "yield": 0.98,
    "change": -0.04,
    "percentChange": "-3.94%",
    "WTDChg": "3.10%",
    "OneMonthChange": "-11.62%",
    "ThreeMonthChange": "-8.67%",
    "TwelveMonthChange": "-4.79%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 1.5,
    "maturityDate": "25-May-31"
  },
  {
    "security": "France 20Y Yield (TPI)",
    "yield": 1.31,
    "change": -0.04,
    "percentChange": "-3.20%",
    "WTDChg": "2.35%",
    "OneMonthChange": "-8.59%",
    "ThreeMonthChange": "-4.66%",
    "TwelveMonthChange": "0.91%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 1.25,
    "maturityDate": "25-May-36"
  },
  {
    "security": "France 25Y Yield (TPI)",
    "yield": 1.42,
    "change": -0.04,
    "percentChange": "-2.85%",
    "WTDChg": "2.36%",
    "OneMonthChange": "-7.34%",
    "ThreeMonthChange": "-3.30%",
    "TwelveMonthChange": "4.19%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 4.5,
    "maturityDate": "25-Apr-41"
  },
  {
    "security": "France 30Y Yield (TPI)",
    "yield": 1.72,
    "change": -0.04,
    "percentChange": "-2.52%",
    "WTDChg": "2.20%",
    "OneMonthChange": "-5.26%",
    "ThreeMonthChange": "-1.27%",
    "TwelveMonthChange": "14.81%",
    "modDur": "--",
    "moodysRating": "Aa2",
    "coupon": 2,
    "maturityDate": "25-May-48"
  },
  {
    "security": "Germany 1Y Yield (TPI)",
    "yield": -0.76,
    "change": -0.03,
    "percentChange": "3.74%",
    "WTDChg": "0.69%",
    "OneMonthChange": "1.99%",
    "ThreeMonthChange": "5.94%",
    "TwelveMonthChange": "7.49%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 1,
    "maturityDate": "12-Oct-18"
  },
  {
    "security": "Germany 2Y Yield (TPI)",
    "yield": -0.76,
    "change": -0.02,
    "percentChange": "2.87%",
    "WTDChg": "-0.17%",
    "OneMonthChange": "7.86%",
    "ThreeMonthChange": "5.90%",
    "TwelveMonthChange": "22.68%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0,
    "maturityDate": "13-Sep-19"
  },
  {
    "security": "Germany 3Y Yield (TPI)",
    "yield": -0.67,
    "change": -0.02,
    "percentChange": "3.19%",
    "WTDChg": "-0.54%",
    "OneMonthChange": "10.67%",
    "ThreeMonthChange": "11.93%",
    "TwelveMonthChange": "13.92%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0.25,
    "maturityDate": "16-Oct-20"
  },
  {
    "security": "Germany 4Y Yield (TPI)",
    "yield": -0.52,
    "change": -0.02,
    "percentChange": "4.51%",
    "WTDChg": "-3.20%",
    "OneMonthChange": "14.05%",
    "ThreeMonthChange": "16.16%",
    "TwelveMonthChange": "13.26%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 2.5,
    "maturityDate": "08-Oct-21"
  },
  {
    "security": "Germany 5Y Yield (TPI)",
    "yield": -0.36,
    "change": -0.03,
    "percentChange": "9.69%",
    "WTDChg": "-4.97%",
    "OneMonthChange": "29.02%",
    "ThreeMonthChange": "27.65%",
    "TwelveMonthChange": "9.13%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0,
    "maturityDate": "07-Oct-22"
  },
  {
    "security": "Germany 6Y Yield (TPI)",
    "yield": -0.24,
    "change": -0.03,
    "percentChange": "16.01%",
    "WTDChg": "-10.02%",
    "OneMonthChange": "47.11%",
    "ThreeMonthChange": "30.72%",
    "TwelveMonthChange": "-13.22%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 2,
    "maturityDate": "15-Aug-23"
  },
  {
    "security": "Germany 7Y Yield (TPI)",
    "yield": -0.09,
    "change": -0.04,
    "percentChange": "66.67%",
    "WTDChg": "-24.28%",
    "OneMonthChange": "245.86%",
    "ThreeMonthChange": "115.96%",
    "TwelveMonthChange": "-37.63%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 1,
    "maturityDate": "15-Aug-24"
  },
  {
    "security": "Germany 8Y Yield (TPI)",
    "yield": 0.04,
    "change": -0.04,
    "percentChange": "-50.33%",
    "WTDChg": "357.83%",
    "OneMonthChange": "-67.96%",
    "ThreeMonthChange": "-63.81%",
    "TwelveMonthChange": "317.58%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 1,
    "maturityDate": "15-Aug-25"
  },
  {
    "security": "Germany 9Y Yield (TPI)",
    "yield": 0.2,
    "change": -0.04,
    "percentChange": "-16.00%",
    "WTDChg": "22.31%",
    "OneMonthChange": "-30.22%",
    "ThreeMonthChange": "-25.50%",
    "TwelveMonthChange": "36.68%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0.5,
    "maturityDate": "15-Aug-26"
  },
  {
    "security": "Germany 10Y Yield (TPI)",
    "yield": 0.36,
    "change": -0.04,
    "percentChange": "-10.03%",
    "WTDChg": "9.35%",
    "OneMonthChange": "-19.61%",
    "ThreeMonthChange": "-12.29%",
    "TwelveMonthChange": "16.14%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0.5,
    "maturityDate": "15-Aug-27"
  },
  {
    "security": "Germany 15Y Yield (TPI)",
    "yield": 0.6,
    "change": -0.04,
    "percentChange": "-6.10%",
    "WTDChg": "7.19%",
    "OneMonthChange": "-9.68%",
    "ThreeMonthChange": "0.20%",
    "TwelveMonthChange": "21.40%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 5.5,
    "maturityDate": "04-Jan-31"
  },
  {
    "security": "Germany 20Y Yield (TPI)",
    "yield": 0.91,
    "change": -0.04,
    "percentChange": "-4.38%",
    "WTDChg": "4.83%",
    "OneMonthChange": "-5.70%",
    "ThreeMonthChange": "3.97%",
    "TwelveMonthChange": "28.89%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 4,
    "maturityDate": "04-Jan-37"
  },
  {
    "security": "Germany 25Y Yield (TPI)",
    "yield": 1.08,
    "change": -0.04,
    "percentChange": "-3.78%",
    "WTDChg": "4.15%",
    "OneMonthChange": "-4.63%",
    "ThreeMonthChange": "2.56%",
    "TwelveMonthChange": "27.47%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 3.25,
    "maturityDate": "04-Jul-42"
  },
  {
    "security": "Germany 30Y Yield (TPI)",
    "yield": 1.25,
    "change": -0.04,
    "percentChange": "-3.26%",
    "WTDChg": "3.53%",
    "OneMonthChange": "-3.70%",
    "ThreeMonthChange": "7.82%",
    "TwelveMonthChange": "35.59%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 1.25,
    "maturityDate": "15-Aug-48"
  },
  {
    "security": "Italy 1Y Yield (TPI)",
    "yield": -0.38,
    "change": -0.04,
    "percentChange": "12.10%",
    "WTDChg": "5.92%",
    "OneMonthChange": "14.53%",
    "ThreeMonthChange": "12.21%",
    "TwelveMonthChange": "80.08%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 3.5,
    "maturityDate": "14-Nov-18"
  },
  {
    "security": "Italy 2Y Yield (TPI)",
    "yield": -0.32,
    "change": -0.03,
    "percentChange": "9.36%",
    "WTDChg": "0.47%",
    "OneMonthChange": "45.59%",
    "ThreeMonthChange": "41.97%",
    "TwelveMonthChange": "-637.82%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 0.1,
    "maturityDate": "15-Apr-19"
  },
  {
    "security": "Italy 3Y Yield (TPI)",
    "yield": -0.06,
    "change": -0.02,
    "percentChange": "46.17%",
    "WTDChg": "-14.05%",
    "OneMonthChange": "-152.24%",
    "ThreeMonthChange": "-144.78%",
    "TwelveMonthChange": "-123.40%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 0.35,
    "maturityDate": "15-Jun-20"
  },
  {
    "security": "Italy 4Y Yield (TPI)",
    "yield": 0.16,
    "change": -0.02,
    "percentChange": "-12.31%",
    "WTDChg": "28.82%",
    "OneMonthChange": "-54.81%",
    "ThreeMonthChange": "-55.99%",
    "TwelveMonthChange": "-71.01%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 3.75,
    "maturityDate": "01-May-21"
  },
  {
    "security": "Italy 5Y Yield (TPI)",
    "yield": 0.57,
    "change": -0.01,
    "percentChange": "-1.83%",
    "WTDChg": "9.03%",
    "OneMonthChange": "-30.29%",
    "ThreeMonthChange": "-17.57%",
    "TwelveMonthChange": "-32.15%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 0.9,
    "maturityDate": "01-Aug-22"
  },
  {
    "security": "Italy 6Y Yield (TPI)",
    "yield": 0.74,
    "change": -0.01,
    "percentChange": "-1.81%",
    "WTDChg": "6.70%",
    "OneMonthChange": "-24.59%",
    "ThreeMonthChange": "-25.97%",
    "TwelveMonthChange": "-31.85%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 0.95,
    "maturityDate": "15-Mar-23"
  },
  {
    "security": "Italy 7Y Yield (TPI)",
    "yield": 1.1,
    "change": -0.01,
    "percentChange": "-1.27%",
    "WTDChg": "5.09%",
    "OneMonthChange": "-20.90%",
    "ThreeMonthChange": "-21.13%",
    "TwelveMonthChange": "-11.04%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 1.85,
    "maturityDate": "15-May-24"
  },
  {
    "security": "Italy 8Y Yield (TPI)",
    "yield": 1.38,
    "change": -0.01,
    "percentChange": "-0.92%",
    "WTDChg": "4.71%",
    "OneMonthChange": "-17.03%",
    "ThreeMonthChange": "-14.90%",
    "TwelveMonthChange": "-14.83%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 1.5,
    "maturityDate": "01-Jun-25"
  },
  {
    "security": "Italy 9Y Yield (TPI)",
    "yield": 1.6,
    "change": -0.01,
    "percentChange": "-0.86%",
    "WTDChg": "5.08%",
    "OneMonthChange": "-14.51%",
    "ThreeMonthChange": "-12.55%",
    "TwelveMonthChange": "-8.58%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 1.6,
    "maturityDate": "01-Jun-26"
  },
  {
    "security": "Italy 10Y Yield (TPI)",
    "yield": 1.81,
    "change": -0.01,
    "percentChange": "-0.74%",
    "WTDChg": "4.30%",
    "OneMonthChange": "-14.32%",
    "ThreeMonthChange": "-9.79%",
    "TwelveMonthChange": "-8.03%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 2.05,
    "maturityDate": "01-Aug-27"
  },
  {
    "security": "Italy 15Y Yield (TPI)",
    "yield": 2.4,
    "change": -0.01,
    "percentChange": "-0.60%",
    "WTDChg": "3.22%",
    "OneMonthChange": "-9.75%",
    "ThreeMonthChange": "-6.72%",
    "TwelveMonthChange": "5.77%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 2.45,
    "maturityDate": "01-Sep-33"
  },
  {
    "security": "Italy 20Y Yield (TPI)",
    "yield": 2.54,
    "change": -0.02,
    "percentChange": "-0.63%",
    "WTDChg": "2.71%",
    "OneMonthChange": "-9.34%",
    "ThreeMonthChange": "-5.86%",
    "TwelveMonthChange": "-1.52%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 2.25,
    "maturityDate": "01-Sep-36"
  },
  {
    "security": "Italy 25Y Yield (TPI)",
    "yield": 2.87,
    "change": -0.01,
    "percentChange": "-0.28%",
    "WTDChg": "3.82%",
    "OneMonthChange": "-8.39%",
    "ThreeMonthChange": "-5.51%",
    "TwelveMonthChange": "-3.54%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 5,
    "maturityDate": "01-Sep-40"
  },
  {
    "security": "Italy 30Y Yield (TPI)",
    "yield": 2.99,
    "change": -0.01,
    "percentChange": "-0.28%",
    "WTDChg": "2.68%",
    "OneMonthChange": "-7.69%",
    "ThreeMonthChange": "-5.20%",
    "TwelveMonthChange": "-1.57%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 2.7,
    "maturityDate": "01-Mar-47"
  },
  {
    "security": "Japan 1Y Yield (TPI)",
    "yield": -0.2,
    "change": 0,
    "percentChange": "-0.15%",
    "WTDChg": "-6.81%",
    "OneMonthChange": "24.63%",
    "ThreeMonthChange": "56.17%",
    "TwelveMonthChange": "-34.78%",
    "modDur": "--",
    "moodysRating": "A1",
    "coupon": 0.1,
    "maturityDate": "15-Oct-18"
  },
  {
    "security": "Japan 2Y Yield (TPI)",
    "yield": -0.19,
    "change": 0,
    "percentChange": "1.11%",
    "WTDChg": "-8.38%",
    "OneMonthChange": "26.94%",
    "ThreeMonthChange": "66.20%",
    "TwelveMonthChange": "-3.29%",
    "modDur": "--",
    "moodysRating": "A1",
    "coupon": 0.1,
    "maturityDate": "15-Nov-19"
  },
  {
    "security": "Japan 3Y Yield (TPI)",
    "yield": -0.16,
    "change": 0,
    "percentChange": "1.73%",
    "WTDChg": "-6.80%",
    "OneMonthChange": "24.73%",
    "ThreeMonthChange": "47.13%",
    "TwelveMonthChange": "-14.80%",
    "modDur": "--",
    "moodysRating": "A1",
    "coupon": 0.1,
    "maturityDate": "20-Sep-20"
  },
  {
    "security": "Japan 4Y Yield (TPI)",
    "yield": -0.13,
    "change": 0,
    "percentChange": "3.75%",
    "WTDChg": "-10.72%",
    "OneMonthChange": "24.43%",
    "ThreeMonthChange": "47.61%",
    "TwelveMonthChange": "-14.26%",
    "modDur": "--",
    "moodysRating": "A1",
    "coupon": 0.1,
    "maturityDate": "20-Sep-21"
  },
  {
    "security": "Japan 5Y Yield (TPI)",
    "yield": -0.12,
    "change": 0,
    "percentChange": "1.83%",
    "WTDChg": "-14.88%",
    "OneMonthChange": "25.08%",
    "ThreeMonthChange": "51.17%",
    "TwelveMonthChange": "-11.12%",
    "modDur": "--",
    "moodysRating": "A1",
    "coupon": 0.1,
    "maturityDate": "20-Sep-22"
  },
  {
    "security": "Japan 6Y Yield (TPI)",
    "yield": -0.08,
    "change": 0,
    "percentChange": "0.87%",
    "WTDChg": "-19.39%",
    "OneMonthChange": "18.12%",
    "ThreeMonthChange": "40.52%",
    "TwelveMonthChange": "-27.56%",
    "modDur": "--",
    "moodysRating": "A1",
    "coupon": 0.8,
    "maturityDate": "20-Sep-23"
  },
  {
    "security": "Japan 7Y Yield (TPI)",
    "yield": -0.06,
    "change": 0,
    "percentChange": "2.45%",
    "WTDChg": "-27.82%",
    "OneMonthChange": "67.02%",
    "ThreeMonthChange": "59.80%",
    "TwelveMonthChange": "-39.03%",
    "modDur": "--",
    "moodysRating": "A1",
    "coupon": 0.3,
    "maturityDate": "20-Dec-24"
  },
  {
    "security": "Japan 8Y Yield (TPI)",
    "yield": -0.03,
    "change": 0,
    "percentChange": "4.79%",
    "WTDChg": "-42.46%",
    "OneMonthChange": "209.43%",
    "ThreeMonthChange": "114.38%",
    "TwelveMonthChange": "-57.35%",
    "modDur": "--",
    "moodysRating": "A1",
    "coupon": 0.4,
    "maturityDate": "20-Sep-25"
  },
  {
    "security": "Japan 9Y Yield (TPI)",
    "yield": 0,
    "change": 0,
    "percentChange": "-13.51%",
    "WTDChg": "-120.00%",
    "OneMonthChange": "-85.05%",
    "ThreeMonthChange": "-80.84%",
    "TwelveMonthChange": "-106.29%",
    "modDur": "--",
    "moodysRating": "A1",
    "coupon": 0.1,
    "maturityDate": "20-Sep-26"
  },
  {
    "security": "Japan 10Y Yield (TPI)",
    "yield": 0.04,
    "change": 0,
    "percentChange": "-8.52%",
    "WTDChg": "98.94%",
    "OneMonthChange": "-34.61%",
    "ThreeMonthChange": "-16.44%",
    "TwelveMonthChange": "-500.00%",
    "modDur": "--",
    "moodysRating": "A1",
    "coupon": 0.1,
    "maturityDate": "20-Sep-27"
  },
  {
    "security": "Japan 15Y Yield (TPI)",
    "yield": 0.28,
    "change": 0,
    "percentChange": "0.18%",
    "WTDChg": "6.02%",
    "OneMonthChange": "-0.64%",
    "ThreeMonthChange": "10.20%",
    "TwelveMonthChange": "88.61%",
    "modDur": "--",
    "moodysRating": "A1",
    "coupon": 1.7,
    "maturityDate": "20-Sep-32"
  },
  {
    "security": "Japan 20Y Yield (TPI)",
    "yield": 0.57,
    "change": -0.01,
    "percentChange": "-0.95%",
    "WTDChg": "1.76%",
    "OneMonthChange": "-1.00%",
    "ThreeMonthChange": "3.78%",
    "TwelveMonthChange": "33.65%",
    "modDur": "--",
    "moodysRating": "A1",
    "coupon": 0.6,
    "maturityDate": "20-Sep-37"
  },
  {
    "security": "Japan 30Y Yield (TPI)",
    "yield": 0.81,
    "change": 0,
    "percentChange": "-0.55%",
    "WTDChg": "3.15%",
    "OneMonthChange": "-5.43%",
    "ThreeMonthChange": "-2.52%",
    "TwelveMonthChange": "44.64%",
    "modDur": "--",
    "moodysRating": "A1",
    "coupon": 0.8,
    "maturityDate": "20-Sep-47"
  },
  {
    "security": "Japan 40Y Yield (TPI)",
    "yield": 0.98,
    "change": 0,
    "percentChange": "-0.46%",
    "WTDChg": "1.65%",
    "OneMonthChange": "-8.57%",
    "ThreeMonthChange": "-6.41%",
    "TwelveMonthChange": "46.60%",
    "modDur": "--",
    "moodysRating": "A1",
    "coupon": 0.9,
    "maturityDate": "20-Mar-57"
  },
  {
    "security": "New Zealand 2Y Yield (TPI)",
    "yield": 2.01,
    "change": -0.02,
    "percentChange": "-1.04%",
    "WTDChg": "-1.25%",
    "OneMonthChange": "-2.41%",
    "ThreeMonthChange": "6.15%",
    "TwelveMonthChange": "7.27%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 3,
    "maturityDate": "15-Apr-20"
  },
  {
    "security": "New Zealand 3Y Yield (TPI)",
    "yield": "--",
    "change": "--",
    "percentChange": "--",
    "WTDChg": "--",
    "OneMonthChange": "--",
    "ThreeMonthChange": "--",
    "TwelveMonthChange": "--",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": "--",
    "maturityDate": "--"
  },
  {
    "security": "New Zealand 5Y Yield (TPI)",
    "yield": 2.45,
    "change": -0.02,
    "percentChange": "-0.98%",
    "WTDChg": "-0.59%",
    "OneMonthChange": "-2.95%",
    "ThreeMonthChange": "0.66%",
    "TwelveMonthChange": "-0.28%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 5.5,
    "maturityDate": "15-Apr-23"
  },
  {
    "security": "New Zealand 7Y Yield (TPI)",
    "yield": "--",
    "change": "--",
    "percentChange": "--",
    "WTDChg": "--",
    "OneMonthChange": "--",
    "ThreeMonthChange": "--",
    "TwelveMonthChange": "--",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": "--",
    "maturityDate": "--"
  },
  {
    "security": "New Zealand 10Y Yield (TPI)",
    "yield": 2.88,
    "change": -0.05,
    "percentChange": "-1.68%",
    "WTDChg": "-0.78%",
    "OneMonthChange": "-2.92%",
    "ThreeMonthChange": "1.91%",
    "TwelveMonthChange": "-6.39%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 4.5,
    "maturityDate": "15-Apr-27"
  },
  {
    "security": "Norway 1Y Yield (TPI)",
    "yield": "--",
    "change": "--",
    "percentChange": "--",
    "WTDChg": "--",
    "OneMonthChange": "--",
    "ThreeMonthChange": "--",
    "TwelveMonthChange": "--",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": "--",
    "maturityDate": "--"
  },
  {
    "security": "Norway 2Y Yield (TPI)",
    "yield": 0.52,
    "change": -0.03,
    "percentChange": "-5.78%",
    "WTDChg": "-1.78%",
    "OneMonthChange": "-2.80%",
    "ThreeMonthChange": "-12.25%",
    "TwelveMonthChange": "-32.60%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 4.5,
    "maturityDate": "22-May-19"
  },
  {
    "security": "Norway 5Y Yield (TPI)",
    "yield": 1.1,
    "change": -0.05,
    "percentChange": "-4.74%",
    "WTDChg": "-2.24%",
    "OneMonthChange": "15.52%",
    "ThreeMonthChange": "26.66%",
    "TwelveMonthChange": "-3.40%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 2,
    "maturityDate": "24-May-23"
  },
  {
    "security": "Norway 7Y Yield (TPI)",
    "yield": 1.2,
    "change": -0.04,
    "percentChange": "-3.54%",
    "WTDChg": "-0.14%",
    "OneMonthChange": "-3.03%",
    "ThreeMonthChange": "4.39%",
    "TwelveMonthChange": "-10.74%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 3,
    "maturityDate": "14-Mar-24"
  },
  {
    "security": "Norway 10Y Yield (TPI)",
    "yield": 1.52,
    "change": -0.05,
    "percentChange": "-3.05%",
    "WTDChg": "0.41%",
    "OneMonthChange": "-6.98%",
    "ThreeMonthChange": "-2.34%",
    "TwelveMonthChange": "-5.10%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 1.75,
    "maturityDate": "17-Feb-27"
  },
  {
    "security": "Spain 3Y Yield (TPI)",
    "yield": -0.2,
    "change": -0.01,
    "percentChange": "7.10%",
    "WTDChg": "5.21%",
    "OneMonthChange": "86.13%",
    "ThreeMonthChange": "-8.79%",
    "TwelveMonthChange": "-268.53%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 4,
    "maturityDate": "30-Apr-20"
  },
  {
    "security": "Spain 5Y Yield (TPI)",
    "yield": 0.21,
    "change": 0,
    "percentChange": "-2.07%",
    "WTDChg": "13.29%",
    "OneMonthChange": "-36.89%",
    "ThreeMonthChange": "-3.97%",
    "TwelveMonthChange": "-48.14%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 0.4,
    "maturityDate": "30-Apr-22"
  },
  {
    "security": "Spain 7Y Yield (TPI)",
    "yield": 0.87,
    "change": 0,
    "percentChange": "0.41%",
    "WTDChg": "6.78%",
    "OneMonthChange": "-9.85%",
    "ThreeMonthChange": "21.52%",
    "TwelveMonthChange": "-0.50%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 2.75,
    "maturityDate": "31-Oct-24"
  },
  {
    "security": "Spain 8Y Yield (TPI)",
    "yield": 1.13,
    "change": 0,
    "percentChange": "0.17%",
    "WTDChg": "5.06%",
    "OneMonthChange": "-8.37%",
    "ThreeMonthChange": "14.28%",
    "TwelveMonthChange": "-0.69%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 2.15,
    "maturityDate": "31-Oct-25"
  },
  {
    "security": "Spain 9Y Yield (TPI)",
    "yield": 1.31,
    "change": 0,
    "percentChange": "0.28%",
    "WTDChg": "4.40%",
    "OneMonthChange": "-7.58%",
    "ThreeMonthChange": "7.88%",
    "TwelveMonthChange": "-0.65%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 1.3,
    "maturityDate": "31-Oct-26"
  },
  {
    "security": "Spain 10Y Yield (TPI)",
    "yield": 1.53,
    "change": 0.01,
    "percentChange": "0.48%",
    "WTDChg": "3.92%",
    "OneMonthChange": "-6.62%",
    "ThreeMonthChange": "7.90%",
    "TwelveMonthChange": "5.01%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 1.45,
    "maturityDate": "31-Oct-27"
  },
  {
    "security": "Spain 15Y Yield (TPI)",
    "yield": "--",
    "change": "--",
    "percentChange": "--",
    "WTDChg": "--",
    "OneMonthChange": "--",
    "ThreeMonthChange": "--",
    "TwelveMonthChange": "--",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": "--",
    "maturityDate": "--"
  },
  {
    "security": "Spain 20Y Yield (TPI)",
    "yield": 2.33,
    "change": 0.01,
    "percentChange": "0.26%",
    "WTDChg": "2.84%",
    "OneMonthChange": "-3.47%",
    "ThreeMonthChange": "3.10%",
    "TwelveMonthChange": "6.10%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 4.2,
    "maturityDate": "31-Jan-37"
  },
  {
    "security": "Spain 30Y Yield (TPI)",
    "yield": 2.81,
    "change": 0.01,
    "percentChange": "0.23%",
    "WTDChg": "2.69%",
    "OneMonthChange": "-2.29%",
    "ThreeMonthChange": "3.56%",
    "TwelveMonthChange": "6.85%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 2.9,
    "maturityDate": "31-Oct-46"
  },
  {
    "security": "Spain 2Y Yield (TPI)",
    "yield": -0.37,
    "change": -0.01,
    "percentChange": "3.09%",
    "WTDChg": "2.83%",
    "OneMonthChange": "29.64%",
    "ThreeMonthChange": "-0.65%",
    "TwelveMonthChange": "181.44%",
    "modDur": "--",
    "moodysRating": "Baa2",
    "coupon": 2.75,
    "maturityDate": "30-Apr-19"
  },
  {
    "security": "Sweden 2Y Yield (TPI)",
    "yield": -0.87,
    "change": 0.01,
    "percentChange": "-0.62%",
    "WTDChg": "3.34%",
    "OneMonthChange": "23.54%",
    "ThreeMonthChange": "26.25%",
    "TwelveMonthChange": "24.00%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 4.25,
    "maturityDate": "12-Mar-19"
  },
  {
    "security": "Sweden 3Y Yield (TPI)",
    "yield": "--",
    "change": "--",
    "percentChange": "--",
    "WTDChg": "--",
    "OneMonthChange": "--",
    "ThreeMonthChange": "--",
    "TwelveMonthChange": "--",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": "--",
    "maturityDate": "--"
  },
  {
    "security": "Sweden 4Y Yield (TPI)",
    "yield": "--",
    "change": "--",
    "percentChange": "--",
    "WTDChg": "--",
    "OneMonthChange": "--",
    "ThreeMonthChange": "--",
    "TwelveMonthChange": "--",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": "--",
    "maturityDate": "--"
  },
  {
    "security": "Sweden 5Y Yield (TPI)",
    "yield": -0.21,
    "change": -0.01,
    "percentChange": "6.26%",
    "WTDChg": "13.67%",
    "OneMonthChange": "519.76%",
    "ThreeMonthChange": "491.43%",
    "TwelveMonthChange": "-51.73%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 3.5,
    "maturityDate": "01-Jun-22"
  },
  {
    "security": "Sweden 6Y Yield (TPI)",
    "yield": "--",
    "change": "--",
    "percentChange": "--",
    "WTDChg": "--",
    "OneMonthChange": "--",
    "ThreeMonthChange": "--",
    "TwelveMonthChange": "--",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": "--",
    "maturityDate": "--"
  },
  {
    "security": "Sweden 7Y Yield (TPI)",
    "yield": 0.09,
    "change": -0.01,
    "percentChange": "-10.75%",
    "WTDChg": "-17.26%",
    "OneMonthChange": "-63.59%",
    "ThreeMonthChange": "-56.01%",
    "TwelveMonthChange": "-162.08%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 1.5,
    "maturityDate": "13-Nov-23"
  },
  {
    "security": "Sweden 8Y Yield (TPI)",
    "yield": "--",
    "change": "--",
    "percentChange": "--",
    "WTDChg": "--",
    "OneMonthChange": "--",
    "ThreeMonthChange": "--",
    "TwelveMonthChange": "--",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": "--",
    "maturityDate": "--"
  },
  {
    "security": "Sweden 9Y Yield (TPI)",
    "yield": 0.51,
    "change": -0.03,
    "percentChange": "-5.26%",
    "WTDChg": "-2.86%",
    "OneMonthChange": "-23.48%",
    "ThreeMonthChange": "20.19%",
    "TwelveMonthChange": "963.03%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 1,
    "maturityDate": "12-Nov-26"
  },
  {
    "security": "Sweden 10Y Yield (TPI)",
    "yield": 0.74,
    "change": -0.04,
    "percentChange": "-4.84%",
    "WTDChg": "-3.10%",
    "OneMonthChange": "-16.78%",
    "ThreeMonthChange": "21.14%",
    "TwelveMonthChange": "53.04%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0.75,
    "maturityDate": "12-May-28"
  },
  {
    "security": "Sweden 30Y Yield (TPI)",
    "yield": 1.46,
    "change": -0.04,
    "percentChange": "-2.64%",
    "WTDChg": "-1.82%",
    "OneMonthChange": "-8.90%",
    "ThreeMonthChange": "-4.18%",
    "TwelveMonthChange": "4.42%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 3.5,
    "maturityDate": "30-Mar-39"
  },
  {
    "security": "CH 1Y Yield (SWX)",
    "yield": -0.88,
    "change": 0,
    "percentChange": "0.43%",
    "WTDChg": "3.33%",
    "OneMonthChange": "--",
    "ThreeMonthChange": "--",
    "TwelveMonthChange": "-7.15%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 3,
    "maturityDate": "12-May-19"
  },
  {
    "security": "CH 2Y Yield (SWX)",
    "yield": -0.85,
    "change": 0,
    "percentChange": "0.00%",
    "WTDChg": "--",
    "OneMonthChange": "7.03%",
    "ThreeMonthChange": "5.92%",
    "TwelveMonthChange": "0.14%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 3,
    "maturityDate": "12-May-19"
  },
  {
    "security": "CH 3Y Yield (SWX)",
    "yield": -0.77,
    "change": 0,
    "percentChange": "0.63%",
    "WTDChg": "1.53%",
    "OneMonthChange": "7.32%",
    "ThreeMonthChange": "4.75%",
    "TwelveMonthChange": "--",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 2.25,
    "maturityDate": "06-Jul-20"
  },
  {
    "security": "CH 4Y Yield (SWX)",
    "yield": -0.6,
    "change": 0,
    "percentChange": "0.00%",
    "WTDChg": "--",
    "OneMonthChange": "-3.24%",
    "ThreeMonthChange": "-6.12%",
    "TwelveMonthChange": "-16.66%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 2,
    "maturityDate": "28-Apr-21"
  },
  {
    "security": "CH 5Y Yield (SWX)",
    "yield": -0.46,
    "change": -0.01,
    "percentChange": "3.28%",
    "WTDChg": "7.73%",
    "OneMonthChange": "12.34%",
    "ThreeMonthChange": "7.91%",
    "TwelveMonthChange": "-8.18%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 4,
    "maturityDate": "11-Feb-23"
  },
  {
    "security": "CH 7Y Yield (SWX)",
    "yield": -0.26,
    "change": -0.02,
    "percentChange": "6.96%",
    "WTDChg": "13.78%",
    "OneMonthChange": "28.93%",
    "ThreeMonthChange": "-26.43%",
    "TwelveMonthChange": "-11.58%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 1.5,
    "maturityDate": "24-Jul-25"
  },
  {
    "security": "CH 10Y Yield (SWX)",
    "yield": -0.02,
    "change": -0.02,
    "percentChange": "1893.63%",
    "WTDChg": "-328.47%",
    "OneMonthChange": "10.01%",
    "ThreeMonthChange": "-73.02%",
    "TwelveMonthChange": "-83.44%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 4,
    "maturityDate": "08-Apr-28"
  },
  {
    "security": "CH 20Y Yield (SWX)",
    "yield": 0.29,
    "change": -0.02,
    "percentChange": "-5.48%",
    "WTDChg": "-9.31%",
    "OneMonthChange": "-5.53%",
    "ThreeMonthChange": "31.55%",
    "TwelveMonthChange": "35.53%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 1.25,
    "maturityDate": "27-Jun-37"
  },
  {
    "security": "Netherlands 1Y Yield (TPI)",
    "yield": -0.76,
    "change": -0.01,
    "percentChange": "1.78%",
    "WTDChg": "-0.50%",
    "OneMonthChange": "5.82%",
    "ThreeMonthChange": "14.23%",
    "TwelveMonthChange": "-0.84%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 4,
    "maturityDate": "15-Jul-18"
  },
  {
    "security": "Netherlands 2Y Yield (TPI)",
    "yield": -0.76,
    "change": -0.02,
    "percentChange": "2.72%",
    "WTDChg": "1.42%",
    "OneMonthChange": "7.48%",
    "ThreeMonthChange": "15.86%",
    "TwelveMonthChange": "18.83%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 4,
    "maturityDate": "15-Jul-19"
  },
  {
    "security": "Netherlands 3Y Yield (TPI)",
    "yield": -0.66,
    "change": -0.01,
    "percentChange": "1.95%",
    "WTDChg": "-1.23%",
    "OneMonthChange": "9.79%",
    "ThreeMonthChange": "15.66%",
    "TwelveMonthChange": "17.56%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 3.5,
    "maturityDate": "15-Jul-20"
  },
  {
    "security": "Netherlands 4Y Yield (TPI)",
    "yield": -0.53,
    "change": -0.02,
    "percentChange": "4.58%",
    "WTDChg": "-1.35%",
    "OneMonthChange": "18.92%",
    "ThreeMonthChange": "18.84%",
    "TwelveMonthChange": "14.48%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 3.25,
    "maturityDate": "15-Jul-21"
  },
  {
    "security": "Netherlands 5Y Yield (TPI)",
    "yield": -0.41,
    "change": -0.03,
    "percentChange": "6.85%",
    "WTDChg": "-3.51%",
    "OneMonthChange": "28.27%",
    "ThreeMonthChange": "26.26%",
    "TwelveMonthChange": "96.56%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 3.5,
    "maturityDate": "15-Jan-22"
  },
  {
    "security": "Netherlands 6Y Yield (TPI)",
    "yield": -0.17,
    "change": -0.03,
    "percentChange": "20.47%",
    "WTDChg": "-9.61%",
    "OneMonthChange": "92.22%",
    "ThreeMonthChange": "58.14%",
    "TwelveMonthChange": "-9.33%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 1.75,
    "maturityDate": "15-Jul-23"
  },
  {
    "security": "Netherlands 7Y Yield (TPI)",
    "yield": -0.01,
    "change": -0.03,
    "percentChange": "-190.28%",
    "WTDChg": "-63.59%",
    "OneMonthChange": "-117.96%",
    "ThreeMonthChange": "-120.16%",
    "TwelveMonthChange": "-50.19%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 2,
    "maturityDate": "15-Jul-24"
  },
  {
    "security": "Netherlands 8Y Yield (TPI)",
    "yield": 0.15,
    "change": -0.03,
    "percentChange": "-17.98%",
    "WTDChg": "19.18%",
    "OneMonthChange": "-38.37%",
    "ThreeMonthChange": "-34.94%",
    "TwelveMonthChange": "3.21%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0.25,
    "maturityDate": "15-Jul-25"
  },
  {
    "security": "Netherlands 9Y Yield (TPI)",
    "yield": 0.3,
    "change": -0.04,
    "percentChange": "-10.81%",
    "WTDChg": "8.96%",
    "OneMonthChange": "-26.11%",
    "ThreeMonthChange": "-21.56%",
    "TwelveMonthChange": "-6.76%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0.5,
    "maturityDate": "15-Jul-26"
  },
  {
    "security": "Netherlands 10Y Yield (TPI)",
    "yield": 0.46,
    "change": -0.03,
    "percentChange": "-6.64%",
    "WTDChg": "7.08%",
    "OneMonthChange": "-17.24%",
    "ThreeMonthChange": "-13.25%",
    "TwelveMonthChange": "2.29%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0.75,
    "maturityDate": "15-Jul-27"
  },
  {
    "security": "Netherlands 15Y Yield (TPI)",
    "yield": 0.82,
    "change": -0.04,
    "percentChange": "-4.39%",
    "WTDChg": "4.87%",
    "OneMonthChange": "-7.49%",
    "ThreeMonthChange": "-0.87%",
    "TwelveMonthChange": "16.35%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 2.5,
    "maturityDate": "15-Jan-33"
  },
  {
    "security": "Netherlands 20Y Yield (TPI)",
    "yield": 0.94,
    "change": -0.04,
    "percentChange": "-3.92%",
    "WTDChg": "4.00%",
    "OneMonthChange": "-6.76%",
    "ThreeMonthChange": "0.31%",
    "TwelveMonthChange": "19.11%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 4,
    "maturityDate": "15-Jan-37"
  },
  {
    "security": "Netherlands 30Y Yield (TPI)",
    "yield": 1.25,
    "change": -0.04,
    "percentChange": "-3.13%",
    "WTDChg": "2.70%",
    "OneMonthChange": "-4.22%",
    "ThreeMonthChange": "2.24%",
    "TwelveMonthChange": "24.49%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 2.75,
    "maturityDate": "15-Jan-47"
  },
  {
    "security": "US 1M T-Bill Yield (TPI)",
    "yield": 1.06,
    "change": 0,
    "percentChange": "0.48%",
    "WTDChg": "0.73%",
    "OneMonthChange": "10.06%",
    "ThreeMonthChange": "11.85%",
    "TwelveMonthChange": "249.78%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0,
    "maturityDate": "14-Dec-17"
  },
  {
    "security": "US 3M T-Bill Yield (TPI)",
    "yield": 1.27,
    "change": 0.01,
    "percentChange": "0.60%",
    "WTDChg": "2.90%",
    "OneMonthChange": "17.24%",
    "ThreeMonthChange": "23.34%",
    "TwelveMonthChange": "155.87%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0,
    "maturityDate": "15-Feb-18"
  },
  {
    "security": "US 6M T-Bill Yield (TPI)",
    "yield": 1.39,
    "change": -0.01,
    "percentChange": "-0.56%",
    "WTDChg": "3.44%",
    "OneMonthChange": "11.08%",
    "ThreeMonthChange": "24.31%",
    "TwelveMonthChange": "123.35%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0,
    "maturityDate": "17-May-18"
  },
  {
    "security": "US 1Y T-Note Yield (TPI)",
    "yield": 1.55,
    "change": -0.01,
    "percentChange": "-0.50%",
    "WTDChg": "1.51%",
    "OneMonthChange": "10.17%",
    "ThreeMonthChange": "27.44%",
    "TwelveMonthChange": "103.21%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0,
    "maturityDate": "08-Nov-18"
  },
  {
    "security": "US 2Y T-Note Yield (TPI)",
    "yield": 1.68,
    "change": -0.01,
    "percentChange": "-0.71%",
    "WTDChg": "1.82%",
    "OneMonthChange": "10.71%",
    "ThreeMonthChange": "27.01%",
    "TwelveMonthChange": "67.81%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0,
    "maturityDate": "31-Oct-19"
  },
  {
    "security": "US 3Y T-Note Yield (TPI)",
    "yield": 1.79,
    "change": -0.02,
    "percentChange": "-1.04%",
    "WTDChg": "1.07%",
    "OneMonthChange": "7.51%",
    "ThreeMonthChange": "21.29%",
    "TwelveMonthChange": "40.47%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0,
    "maturityDate": "15-Nov-20"
  },
  {
    "security": "US 5Y T-Note Yield (TPI)",
    "yield": 2.03,
    "change": -0.03,
    "percentChange": "-1.62%",
    "WTDChg": "0.75%",
    "OneMonthChange": "4.57%",
    "ThreeMonthChange": "14.43%",
    "TwelveMonthChange": "22.14%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0,
    "maturityDate": "31-Oct-22"
  },
  {
    "security": "US 7Y T-Note Yield (TPI)",
    "yield": 2.21,
    "change": -0.04,
    "percentChange": "-1.95%",
    "WTDChg": "0.00%",
    "OneMonthChange": "2.41%",
    "ThreeMonthChange": "8.51%",
    "TwelveMonthChange": "10.05%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0,
    "maturityDate": "31-Oct-24"
  },
  {
    "security": "US 10Y T-Note Yield (TPI)",
    "yield": 2.33,
    "change": -0.04,
    "percentChange": "-1.72%",
    "WTDChg": "-0.37%",
    "OneMonthChange": "0.48%",
    "ThreeMonthChange": "5.07%",
    "TwelveMonthChange": "5.05%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0,
    "maturityDate": "15-Nov-27"
  },
  {
    "security": "US 30Y T-Bond Yield (TPI)",
    "yield": 2.79,
    "change": -0.04,
    "percentChange": "-1.50%",
    "WTDChg": "-1.27%",
    "OneMonthChange": "-2.15%",
    "ThreeMonthChange": "-0.68%",
    "TwelveMonthChange": "-5.75%",
    "modDur": "--",
    "moodysRating": "Aaa",
    "coupon": 0,
    "maturityDate": "15-Nov-47"
  }
]