apiVersion: v1
kind: Namespace
metadata:
  name: test-reactive-analytics

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reactive-analytics-client
  namespace: test-reactive-analytics
  name: analytics-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactive-analytics-client
  template:
    metadata:
      labels:
        app: reactive-analytics-client
    spec:
      containers:
        - name: client
          image: eu.gcr.io/adaptive-reactive-analytics/reactive-analytics-client:0.6
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reactive-analytics-client
  namespace: test-reactive-analytics
  name: analytics-client
spec:
  selector:
    app: reactive-analytics-client
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: LoadBalancer
