apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reactive-analytics-client
  name: analytics-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactive-analytics-client
  template:
    metadata:
      labels:
        app: reactive-analytics-client
    spec:
      containers:
        - name: client
          image: ${GOOGLE_GCR_HANDLE}/${GOOGLE_PROJECT_ID}/reactive-analytics-client:${BUILD_VERSION}
          ports:
            - containerPort: 3000
          env:
            - name: ENVIRONMENT_NAME
              valueFrom:
                configMapKeyRef:
                  name: analytics-client-config
                  key: environment-name
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reactive-analytics-client
  name: analytics-client
spec:
  selector:
    app: reactive-analytics-client
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-client-config
  namespace: ${NAMESPACE}
data:
  environment-name: ${ENV}